/* Auto-generated Material bootstrap snapshot.
   Immediate live data while Apps Script reconnects in the background. */
window.MEKICS_BOOTSTRAP_SNAPSHOT = {
  "generatedAt": "2026-09-29T07:02:57.633Z",
  "data": {
    "ok": true,
    "items": [
      {
        "id": "ce69bcc0-08f6-421b-9d55-a913dfd3fe06",
        "product": "OmniOx",
        "no": "1",
        "category": "제품소개",
        "item": "제품 카다로그",
        "description": "제품 라인업 및 주요 사양을 소개하는 자료",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 1
      },
      {
        "id": "7e975d0a-9f40-427f-9da7-610f77e727c6",
        "product": "OmniOx",
        "no": "1-1.",
        "category": "",
        "item": "OmniOx",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-09",
        "note": "",
        "order": 2
      },
      {
        "id": "b219e5c8-6e81-44bb-8c1f-93dd07557b6a",
        "product": "OmniOx",
        "no": "1-2.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-09",
        "note": "",
        "order": 3
      },
      {
        "id": "10f1290e-43e4-47cf-bb18-dfffab92d0bc",
        "product": "OmniOx",
        "no": "1-3.",
        "category": "",
        "item": "HFT750A",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-14",
        "note": "",
        "order": 4
      },
      {
        "id": "904be202-f493-46b2-927b-0dc72e8d4658",
        "product": "OmniOx",
        "no": "1-4.",
        "category": "",
        "item": "HFT750B",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-14",
        "note": "",
        "order": 5
      },
      {
        "id": "122ac44e-cc7c-4728-999f-4e53231a5a1e",
        "product": "OmniOx",
        "no": "1-5.",
        "category": "",
        "item": "HFT750S",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-14",
        "note": "",
        "order": 6
      },
      {
        "id": "9691da37-13bf-48b0-b998-7c1084e63aa1",
        "product": "OmniOx",
        "no": "1-6.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-14",
        "note": "이미지 저작권 재 확인",
        "order": 7
      },
      {
        "id": "91e1a3ae-744a-471d-8642-7fb8bbd792ea",
        "product": "OmniOx",
        "no": "2",
        "category": "제품소개",
        "item": "제품 브로슈어",
        "description": "요약형 홍보물 (영업 방문·전시회용)",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 8
      },
      {
        "id": "a40ff3c8-58c3-408a-8a4c-4e2691508667",
        "product": "OmniOx",
        "no": "2-1.",
        "category": "",
        "item": "OmniOx",
        "description": "",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 9
      },
      {
        "id": "b44763ce-59d0-45c3-abd9-cefadd0ac0c0",
        "product": "OmniOx",
        "no": "2-2.",
        "category": "",
        "item": "Bi-Flow",
        "description": "",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 10
      },
      {
        "id": "3a284a38-00c3-46b3-81ab-15a8f090de14",
        "product": "OmniOx",
        "no": "2-3.",
        "category": "",
        "item": "TSF",
        "description": "",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 11
      },
      {
        "id": "345b6fad-8d73-4d2c-a37d-3c48d2c79fee",
        "product": "OmniOx",
        "no": "3",
        "category": "제품소개",
        "item": "제품 소개 PPT자료",
        "description": "영업 프레젠테이션용 슬라이드",
        "status": "보유",
        "updatedAt": "2026-05-13",
        "note": "디자인 및 내용 재검토",
        "order": 12
      },
      {
        "id": "f68d1619-278e-4231-9243-5b8e1ee2b651",
        "product": "OmniOx",
        "no": "4",
        "category": "사용/설치자료",
        "item": "사용자 매뉴얼",
        "description": "제품 사용법 안내서",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 13
      },
      {
        "id": "994a7c6b-dc68-4ad6-897e-9f99bc6dc02d",
        "product": "OmniOx",
        "no": "4-1.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-09",
        "note": "",
        "order": 14
      },
      {
        "id": "486acf6a-9eed-4b42-bd84-5031541bee63",
        "product": "OmniOx",
        "no": "4-2.",
        "category": "",
        "item": "HFT750A",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-14",
        "note": "",
        "order": 15
      },
      {
        "id": "0c897580-acd7-4b6e-af57-04b532b4a841",
        "product": "OmniOx",
        "no": "4-3.",
        "category": "",
        "item": "HFT750B",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-14",
        "note": "",
        "order": 16
      },
      {
        "id": "a4d58c0e-b24a-429a-aa61-fa46641f90cf",
        "product": "OmniOx",
        "no": "4-4.",
        "category": "",
        "item": "HFT750S",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-14",
        "note": "",
        "order": 17
      },
      {
        "id": "ac80fe01-0eef-4584-8f34-df0c09139c8d",
        "product": "OmniOx",
        "no": "4-5.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-14",
        "note": "",
        "order": 18
      },
      {
        "id": "ee9b41b8-f447-43ed-b197-c27a71073fb3",
        "product": "OmniOx",
        "no": "5",
        "category": "사용/설치자료",
        "item": "퀵 매뉴얼",
        "description": "설치 및 셋업 가이드",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 19
      },
      {
        "id": "443a1958-8750-4180-bead-9700f01dc0a1",
        "product": "OmniOx",
        "no": "5-1.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-09",
        "note": "",
        "order": 20
      },
      {
        "id": "1dfbedf1-6d53-4118-92d5-84e3359c88e6",
        "product": "OmniOx",
        "no": "5-2.",
        "category": "",
        "item": "HFT750A",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-14",
        "note": "",
        "order": 21
      },
      {
        "id": "9352d264-7eb2-4633-9617-0fb2b129aaa3",
        "product": "OmniOx",
        "no": "5-3.",
        "category": "",
        "item": "HFT750B",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-14",
        "note": "",
        "order": 22
      },
      {
        "id": "f704847b-671f-4a7d-92d7-9ded83b856d4",
        "product": "OmniOx",
        "no": "5-4.",
        "category": "",
        "item": "HFT750S",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-14",
        "note": "",
        "order": 23
      },
      {
        "id": "59db0f66-4f68-467c-a1bf-0518c27c28b5",
        "product": "OmniOx",
        "no": "5-5.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "보유",
        "updatedAt": "2026-04-14",
        "note": "",
        "order": 24
      },
      {
        "id": "8870df2e-bb0c-4460-a141-c68daa495bf8",
        "product": "OmniOx",
        "no": "6",
        "category": "사용/설치자료",
        "item": "트러블슈팅/FAQ",
        "description": "자주 묻는 질문 및 문제 해결 안내",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 25
      },
      {
        "id": "009683e2-91f5-4274-94ab-e0ae5eae0188",
        "product": "OmniOx",
        "no": "7",
        "category": "인허가/제출 자료",
        "item": "인증서",
        "description": "제품 인증 및 허가 관련 서류",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 26
      },
      {
        "id": "52d6fcaa-d353-4258-89a2-f6c4b97352a6",
        "product": "OmniOx",
        "no": "8",
        "category": "인허가/제출 자료",
        "item": "임상적 근거자료 (Clinical Evidence)",
        "description": "임상 데이터 및 관련 논문·자료",
        "status": "확인중",
        "updatedAt": "",
        "note": "",
        "order": 27
      },
      {
        "id": "237f2427-2c9e-4708-8d76-04c7230fb407",
        "product": "OmniOx",
        "no": "9",
        "category": "영업지원자료",
        "item": "경쟁사 비교자료",
        "description": "경쟁 제품 대비 강점 비교 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "업데이트본 없음",
        "order": 28
      },
      {
        "id": "22f07fca-2149-419a-962b-b8af9a686d4e",
        "product": "OmniOx",
        "no": "10",
        "category": "영업지원자료",
        "item": "레퍼런스 병원 리스트",
        "description": "기존 설치·사용 병원 레퍼런스",
        "status": "미보유",
        "updatedAt": "",
        "note": "업데이트본 없음",
        "order": 29
      },
      {
        "id": "330799e2-6081-49fd-a310-145ef0fe18e8",
        "product": "OmniOx",
        "no": "11",
        "category": "기타",
        "item": "사용 후기 / 케이스 스터디",
        "description": "고객 사용 사례 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "업데이트본 없음",
        "order": 30
      },
      {
        "id": "a9f9695b-4567-4aa4-ba3e-2eeaa53227cc",
        "product": "OmniOx",
        "no": "12",
        "category": "기타",
        "item": "제품 데모 영상",
        "description": "사용 시연 영상",
        "status": "미보유",
        "updatedAt": "",
        "note": "일부 있으나 전체영상 없음",
        "order": 31
      },
      {
        "id": "15100006-fd47-4ff2-88f8-70ff3a2909ef",
        "product": "OmniOx",
        "no": "13",
        "category": "기타",
        "item": "전시회·학회용 홍보물",
        "description": "부스 전시용 배너, 리플렛 등",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 32
      },
      {
        "id": "bef5d528-13ca-494d-b29d-b6b9ecafe616",
        "product": "MV50",
        "no": "1",
        "category": "제품소개",
        "item": "제품 카다로그",
        "description": "제품 라인업 및 주요 사양을 소개하는 자료",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 33
      },
      {
        "id": "18927fd0-650e-422a-b2e9-40b0b533d669",
        "product": "MV50",
        "no": "2",
        "category": "제품소개",
        "item": "제품 브로슈어",
        "description": "요약형 홍보물 (영업 방문·전시회용)",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 34
      },
      {
        "id": "5d0d84f7-94d5-48fc-b75f-7329a16e0ff3",
        "product": "MV50",
        "no": "3",
        "category": "제품소개",
        "item": "제품 소개 PPT자료",
        "description": "영업 프레젠테이션용 슬라이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 35
      },
      {
        "id": "63560a91-e603-4188-bb1f-ef205eaa4e46",
        "product": "MV50",
        "no": "4",
        "category": "사용/설치자료",
        "item": "사용자 매뉴얼",
        "description": "제품 사용법 안내서",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 36
      },
      {
        "id": "71aab18e-a52a-4895-ad0b-3b07cd25cb0d",
        "product": "MV50",
        "no": "5",
        "category": "사용/설치자료",
        "item": "퀵 매뉴얼",
        "description": "설치 및 셋업 가이드",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 37
      },
      {
        "id": "3c7854b9-f94f-4aba-bb0e-464098ce4299",
        "product": "MV50",
        "no": "6",
        "category": "사용/설치자료",
        "item": "트러블슈팅/FAQ",
        "description": "자주 묻는 질문 및 문제 해결 안내",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 38
      },
      {
        "id": "98aade6b-168e-44ab-9c40-e4dfa6cdfbe2",
        "product": "MV50",
        "no": "7",
        "category": "인허가/제출 자료",
        "item": "임상적 근거자료 (Clinical Evidence)",
        "description": "임상 데이터 및 관련 논문·자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 39
      },
      {
        "id": "9df71c13-3ff5-4e61-92b6-8815b640ab59",
        "product": "MV50",
        "no": "9",
        "category": "영업지원자료",
        "item": "경쟁사 비교자료",
        "description": "경쟁 제품 대비 강점 비교 자료",
        "status": "확인중",
        "updatedAt": "",
        "note": "",
        "order": 40
      },
      {
        "id": "4c1b072d-fda4-4e70-8e53-0a8ba2592e50",
        "product": "MV50",
        "no": "10",
        "category": "영업지원자료",
        "item": "레퍼런스 병원 리스트",
        "description": "기존 설치·사용 병원 레퍼런스",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 41
      },
      {
        "id": "0341311b-6e8b-43c3-b725-f72005e74261",
        "product": "MV50",
        "no": "11",
        "category": "기타",
        "item": "사용 후기 / 케이스 스터디",
        "description": "고객 사용 사례 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 42
      },
      {
        "id": "69f371ae-d6a9-4ed3-8492-0236cfd76a30",
        "product": "MV50",
        "no": "12",
        "category": "기타",
        "item": "제품 데모 영상",
        "description": "사용 시연 영상",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 43
      },
      {
        "id": "60debb71-d55b-46fd-93f9-551200fc6c4c",
        "product": "MV50",
        "no": "13",
        "category": "기타",
        "item": "전시회·학회용 홍보물",
        "description": "부스 전시용 배너, 리플렛 등",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 44
      },
      {
        "id": "287b7d5f-c383-479d-87a6-59f041b69c2d",
        "product": "MTV1000",
        "no": "1",
        "category": "제품소개",
        "item": "제품 카다로그",
        "description": "제품 라인업 및 주요 사양을 소개하는 자료",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 45
      },
      {
        "id": "b4113b45-79b3-4143-8fd8-e7b3d4b18cd2",
        "product": "MTV1000",
        "no": "2",
        "category": "제품소개",
        "item": "제품 브로슈어",
        "description": "요약형 홍보물 (영업 방문·전시회용)",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 46
      },
      {
        "id": "69b604d8-d3ab-4298-a0ae-6e0080821843",
        "product": "MTV1000",
        "no": "3",
        "category": "제품소개",
        "item": "제품 소개 PPT자료",
        "description": "영업 프레젠테이션용 슬라이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 47
      },
      {
        "id": "7d3692f1-262b-4580-a1de-f3a8a7a689b5",
        "product": "MTV1000",
        "no": "4",
        "category": "사용/설치자료",
        "item": "사용자 매뉴얼",
        "description": "제품 사용법 안내서",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 48
      },
      {
        "id": "f9756d1c-1eee-4f0c-9bc0-3de6e6a2bd71",
        "product": "MTV1000",
        "no": "5",
        "category": "사용/설치자료",
        "item": "퀵 매뉴얼",
        "description": "설치 및 셋업 가이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 49
      },
      {
        "id": "1af39085-02ea-4483-bedd-bac2372f0e46",
        "product": "MTV1000",
        "no": "6",
        "category": "사용/설치자료",
        "item": "트러블슈팅/FAQ",
        "description": "자주 묻는 질문 및 문제 해결 안내",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 50
      },
      {
        "id": "aed8019a-9aa8-48f7-8076-3ad0f526fe67",
        "product": "MTV1000",
        "no": "7",
        "category": "인허가/제출 자료",
        "item": "임상적 근거자료 (Clinical Evidence)",
        "description": "임상 데이터 및 관련 논문·자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 51
      },
      {
        "id": "e449cb07-0537-4966-8903-2c502cc551ce",
        "product": "MTV1000",
        "no": "9",
        "category": "영업지원자료",
        "item": "경쟁사 비교자료",
        "description": "경쟁 제품 대비 강점 비교 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 52
      },
      {
        "id": "e35fe589-ec8c-4eed-8c9a-25ac4247406d",
        "product": "MTV1000",
        "no": "10",
        "category": "영업지원자료",
        "item": "레퍼런스 병원 리스트",
        "description": "기존 설치·사용 병원 레퍼런스",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 53
      },
      {
        "id": "16cfb3be-0b6a-49f0-903e-781e92fd5b32",
        "product": "MTV1000",
        "no": "11",
        "category": "기타",
        "item": "사용 후기 / 케이스 스터디",
        "description": "고객 사용 사례 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 54
      },
      {
        "id": "82abd01b-fe5e-4798-ae3e-27b8494a1734",
        "product": "MTV1000",
        "no": "12",
        "category": "기타",
        "item": "제품 데모 영상",
        "description": "사용 시연 영상",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 55
      },
      {
        "id": "5c858336-70d5-4780-b600-2bd967caa930",
        "product": "MTV1000",
        "no": "13",
        "category": "기타",
        "item": "전시회·학회용 홍보물",
        "description": "부스 전시용 배너, 리플렛 등",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 56
      },
      {
        "id": "b60d81ca-3984-4de9-b6d4-ea0ca56f693a",
        "product": "MV2000",
        "no": "1",
        "category": "제품소개",
        "item": "제품 카다로그",
        "description": "제품 라인업 및 주요 사양을 소개하는 자료",
        "status": "보유",
        "updatedAt": "",
        "note": "",
        "order": 57
      },
      {
        "id": "4758ccf0-6a54-478a-ad18-f813a9f34e0c",
        "product": "MV2000",
        "no": "2",
        "category": "제품소개",
        "item": "제품 브로슈어",
        "description": "요약형 홍보물 (영업 방문·전시회용)",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 58
      },
      {
        "id": "a9d2fbe2-5dcc-41d6-a024-e5b112deb5f8",
        "product": "MV2000",
        "no": "3",
        "category": "제품소개",
        "item": "제품 소개 PPT자료",
        "description": "영업 프레젠테이션용 슬라이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 59
      },
      {
        "id": "9c370df5-28ec-40c0-995f-d26079bd76f8",
        "product": "MV2000",
        "no": "4",
        "category": "사용/설치자료",
        "item": "사용자 매뉴얼",
        "description": "제품 사용법 안내서",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 60
      },
      {
        "id": "946bcc57-9070-4267-bb68-4c483bfea2fd",
        "product": "MV2000",
        "no": "5",
        "category": "사용/설치자료",
        "item": "퀵 매뉴얼",
        "description": "설치 및 셋업 가이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 61
      },
      {
        "id": "1d57c96c-26fc-40bd-a6f3-25d55aa187a3",
        "product": "MV2000",
        "no": "6",
        "category": "사용/설치자료",
        "item": "트러블슈팅/FAQ",
        "description": "자주 묻는 질문 및 문제 해결 안내",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 62
      },
      {
        "id": "15acecb5-6a73-4e4e-9129-01c7815ae99b",
        "product": "MV2000",
        "no": "7",
        "category": "인허가/제출 자료",
        "item": "임상적 근거자료 (Clinical Evidence)",
        "description": "임상 데이터 및 관련 논문·자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 63
      },
      {
        "id": "783600a3-e8ab-4d00-b417-ab28c0b6999e",
        "product": "MV2000",
        "no": "9",
        "category": "영업지원자료",
        "item": "경쟁사 비교자료",
        "description": "경쟁 제품 대비 강점 비교 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 64
      },
      {
        "id": "bda99fc0-dfad-4bf1-8e32-7fc9bb1e3e15",
        "product": "MV2000",
        "no": "10",
        "category": "영업지원자료",
        "item": "레퍼런스 병원 리스트",
        "description": "기존 설치·사용 병원 레퍼런스",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 65
      },
      {
        "id": "de359a39-986a-4637-9d24-e241a2fb194c",
        "product": "MV2000",
        "no": "11",
        "category": "기타",
        "item": "사용 후기 / 케이스 스터디",
        "description": "고객 사용 사례 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 66
      },
      {
        "id": "2ea7ae7c-5bdf-47b7-b929-75bb910f4af4",
        "product": "MV2000",
        "no": "12",
        "category": "기타",
        "item": "제품 데모 영상",
        "description": "사용 시연 영상",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 67
      },
      {
        "id": "1a1da025-c7ab-4fe5-9ac0-6e55c03fa049",
        "product": "MV2000",
        "no": "13",
        "category": "기타",
        "item": "전시회·학회용 홍보물",
        "description": "부스 전시용 배너, 리플렛 등",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 68
      },
      {
        "id": "adfcfa68-4d1a-4af9-98cf-572b8c9104c2",
        "product": "MP10/12",
        "no": "1",
        "category": "제품소개",
        "item": "제품 카다로그",
        "description": "제품 라인업 및 주요 사양을 소개하는 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 69
      },
      {
        "id": "fc53e7ae-1e66-47bf-b405-72bcc9b15cdd",
        "product": "MP10/12",
        "no": "2",
        "category": "제품소개",
        "item": "제품 브로슈어",
        "description": "요약형 홍보물 (영업 방문·전시회용)",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 70
      },
      {
        "id": "fc8d3db5-2186-4a2e-a228-e3152fccfcfa",
        "product": "MP10/12",
        "no": "3",
        "category": "제품소개",
        "item": "제품 소개 PPT자료",
        "description": "영업 프레젠테이션용 슬라이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 71
      },
      {
        "id": "d65648bd-76b2-45cf-b198-0be1a7503491",
        "product": "MP10/12",
        "no": "4",
        "category": "사용/설치자료",
        "item": "사용자 매뉴얼",
        "description": "제품 사용법 안내서",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 72
      },
      {
        "id": "79eca783-4d58-4497-967c-5a293a124f37",
        "product": "MP10/12",
        "no": "5",
        "category": "사용/설치자료",
        "item": "퀵 매뉴얼",
        "description": "설치 및 셋업 가이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 73
      },
      {
        "id": "d7ce4477-7626-4f95-b90b-08c2fa25ef75",
        "product": "MP10/12",
        "no": "6",
        "category": "사용/설치자료",
        "item": "트러블슈팅/FAQ",
        "description": "자주 묻는 질문 및 문제 해결 안내",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 74
      },
      {
        "id": "a2790402-bf07-4213-82ea-20d67499ba09",
        "product": "MP10/12",
        "no": "7",
        "category": "인허가/제출 자료",
        "item": "임상적 근거자료 (Clinical Evidence)",
        "description": "임상 데이터 및 관련 논문·자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 75
      },
      {
        "id": "0f689d45-22b0-4097-a6a0-336d4b9f93e9",
        "product": "MP10/12",
        "no": "9",
        "category": "영업지원자료",
        "item": "경쟁사 비교자료",
        "description": "경쟁 제품 대비 강점 비교 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 76
      },
      {
        "id": "c2abad45-802b-4df2-8e69-152814aed63d",
        "product": "MP10/12",
        "no": "10",
        "category": "영업지원자료",
        "item": "레퍼런스 병원 리스트",
        "description": "기존 설치·사용 병원 레퍼런스",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 77
      },
      {
        "id": "4f14b749-0ddf-4c69-8b44-9a49f77b7162",
        "product": "MP10/12",
        "no": "11",
        "category": "기타",
        "item": "사용 후기 / 케이스 스터디",
        "description": "고객 사용 사례 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 78
      },
      {
        "id": "31c19fc8-6dd3-412d-b3c2-398554b7eba4",
        "product": "MP10/12",
        "no": "12",
        "category": "기타",
        "item": "제품 데모 영상",
        "description": "사용 시연 영상",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 79
      },
      {
        "id": "2a6779db-e82b-4662-a5d4-405668dc27a9",
        "product": "MP10/12",
        "no": "13",
        "category": "기타",
        "item": "전시회·학회용 홍보물",
        "description": "부스 전시용 배너, 리플렛 등",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 80
      },
      {
        "id": "ff782e5c-8f9b-431b-b166-0b4df7d68e12",
        "product": "OmniOx",
        "no": "1-7.",
        "category": "제품소개",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "보유",
        "updatedAt": "2026. 9. 18",
        "note": "",
        "order": 81
      },
      {
        "id": "6e7e484e-4625-4340-b90f-bcc83d531bec",
        "product": "OmniOx",
        "no": "2-4.",
        "category": "",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 82
      },
      {
        "id": "842f1dfd-b725-4a0d-ad4b-57c5cd8e3c04",
        "product": "OmniOx",
        "no": "3-1.",
        "category": "",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 83
      },
      {
        "id": "b3653d13-95b4-4c5b-838c-3a2c0aed4ec6",
        "product": "OmniOx",
        "no": "4-6.",
        "category": "",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 84
      },
      {
        "id": "788592a0-2ce9-44ff-994b-17261587f253",
        "product": "OmniOx",
        "no": "5-6.",
        "category": "",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 85
      },
      {
        "id": "4c4e856d-e359-4159-9f37-f821ba9b567a",
        "product": "OmniOx",
        "no": "6-1.",
        "category": "",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 86
      },
      {
        "id": "177440e3-795c-4193-85d3-4a03b49afcf4",
        "product": "OmniOx",
        "no": "7-1.",
        "category": "",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 87
      },
      {
        "id": "4b16d492-f0f3-4bef-82bb-73482f16e176",
        "product": "OmniOx",
        "no": "8-1.",
        "category": "",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 88
      },
      {
        "id": "15e0a316-d9c5-4cad-ba0c-e6a1ee281ea1",
        "product": "OmniOx",
        "no": "9-1.",
        "category": "",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 89
      },
      {
        "id": "5999b5b3-ea9f-4149-ac01-8a04c7ae939e",
        "product": "OmniOx",
        "no": "10-1.",
        "category": "",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 90
      },
      {
        "id": "15f2883c-976e-4c41-9527-8633fe20cac2",
        "product": "OmniOx",
        "no": "11-1.",
        "category": "",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 91
      },
      {
        "id": "5583ccff-801f-49ec-816c-9ee2939dfd19",
        "product": "OmniOx",
        "no": "12-1.",
        "category": "",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 92
      },
      {
        "id": "90831db0-c74b-41d1-9f12-fd3b847ee613",
        "product": "OmniOx",
        "no": "13-1.",
        "category": "",
        "item": "HFT750",
        "description": "해외용 HFT750 단일 모델",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 93
      },
      {
        "id": "std-mp800-1",
        "product": "MP800",
        "no": "1",
        "category": "제품소개",
        "item": "제품 카다로그",
        "description": "제품 라인업 및 주요 사양을 소개하는 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 94
      },
      {
        "id": "std-mp800-2",
        "product": "MP800",
        "no": "2",
        "category": "제품소개",
        "item": "제품 브로슈어",
        "description": "요약형 홍보물 (영업 방문·전시회용)",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 95
      },
      {
        "id": "std-mp800-3",
        "product": "MP800",
        "no": "3",
        "category": "제품소개",
        "item": "제품 소개 PPT자료",
        "description": "영업 프레젠테이션용 슬라이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 96
      },
      {
        "id": "std-mp800-4",
        "product": "MP800",
        "no": "4",
        "category": "사용/설치자료",
        "item": "사용자 매뉴얼",
        "description": "제품 사용법 안내서",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 97
      },
      {
        "id": "std-mp800-5",
        "product": "MP800",
        "no": "5",
        "category": "사용/설치자료",
        "item": "퀵 매뉴얼",
        "description": "설치 및 셋업 가이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 98
      },
      {
        "id": "std-mp800-6",
        "product": "MP800",
        "no": "6",
        "category": "사용/설치자료",
        "item": "트러블슈팅/FAQ",
        "description": "자주 묻는 질문 및 문제 해결 안내",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 99
      },
      {
        "id": "std-mp800-7",
        "product": "MP800",
        "no": "7",
        "category": "인허가/제출 자료",
        "item": "임상적 근거자료 (Clinical Evidence)",
        "description": "임상 데이터 및 관련 논문·자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 100
      },
      {
        "id": "std-mp800-9",
        "product": "MP800",
        "no": "9",
        "category": "영업지원자료",
        "item": "경쟁사 비교자료",
        "description": "경쟁 제품 대비 강점 비교 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 101
      },
      {
        "id": "std-mp800-10",
        "product": "MP800",
        "no": "10",
        "category": "영업지원자료",
        "item": "레퍼런스 병원 리스트",
        "description": "기존 설치·사용 병원 레퍼런스",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 102
      },
      {
        "id": "std-mp800-11",
        "product": "MP800",
        "no": "11",
        "category": "기타",
        "item": "사용 후기 / 케이스 스터디",
        "description": "고객 사용 사례 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 103
      },
      {
        "id": "std-mp800-12",
        "product": "MP800",
        "no": "12",
        "category": "기타",
        "item": "제품 데모 영상",
        "description": "사용 시연 영상",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 104
      },
      {
        "id": "std-mp800-13",
        "product": "MP800",
        "no": "13",
        "category": "기타",
        "item": "전시회·학회용 홍보물",
        "description": "부스 전시용 배너, 리플렛 등",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 105
      },
      {
        "id": "std-mnc100-1",
        "product": "MNC100",
        "no": "1",
        "category": "제품소개",
        "item": "제품 카다로그",
        "description": "제품 라인업 및 주요 사양을 소개하는 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 106
      },
      {
        "id": "std-mnc100-2",
        "product": "MNC100",
        "no": "2",
        "category": "제품소개",
        "item": "제품 브로슈어",
        "description": "요약형 홍보물 (영업 방문·전시회용)",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 107
      },
      {
        "id": "std-mnc100-3",
        "product": "MNC100",
        "no": "3",
        "category": "제품소개",
        "item": "제품 소개 PPT자료",
        "description": "영업 프레젠테이션용 슬라이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 108
      },
      {
        "id": "std-mnc100-4",
        "product": "MNC100",
        "no": "4",
        "category": "사용/설치자료",
        "item": "사용자 매뉴얼",
        "description": "제품 사용법 안내서",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 109
      },
      {
        "id": "std-mnc100-5",
        "product": "MNC100",
        "no": "5",
        "category": "사용/설치자료",
        "item": "퀵 매뉴얼",
        "description": "설치 및 셋업 가이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 110
      },
      {
        "id": "std-mnc100-6",
        "product": "MNC100",
        "no": "6",
        "category": "사용/설치자료",
        "item": "트러블슈팅/FAQ",
        "description": "자주 묻는 질문 및 문제 해결 안내",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 111
      },
      {
        "id": "std-mnc100-7",
        "product": "MNC100",
        "no": "7",
        "category": "인허가/제출 자료",
        "item": "임상적 근거자료 (Clinical Evidence)",
        "description": "임상 데이터 및 관련 논문·자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 112
      },
      {
        "id": "std-mnc100-9",
        "product": "MNC100",
        "no": "9",
        "category": "영업지원자료",
        "item": "경쟁사 비교자료",
        "description": "경쟁 제품 대비 강점 비교 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 113
      },
      {
        "id": "std-mnc100-10",
        "product": "MNC100",
        "no": "10",
        "category": "영업지원자료",
        "item": "레퍼런스 병원 리스트",
        "description": "기존 설치·사용 병원 레퍼런스",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 114
      },
      {
        "id": "std-mnc100-11",
        "product": "MNC100",
        "no": "11",
        "category": "기타",
        "item": "사용 후기 / 케이스 스터디",
        "description": "고객 사용 사례 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 115
      },
      {
        "id": "std-mnc100-12",
        "product": "MNC100",
        "no": "12",
        "category": "기타",
        "item": "제품 데모 영상",
        "description": "사용 시연 영상",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 116
      },
      {
        "id": "std-mnc100-13",
        "product": "MNC100",
        "no": "13",
        "category": "기타",
        "item": "전시회·학회용 홍보물",
        "description": "부스 전시용 배너, 리플렛 등",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 117
      },
      {
        "id": "std-mh100-1",
        "product": "MH100",
        "no": "1",
        "category": "제품소개",
        "item": "제품 카다로그",
        "description": "제품 라인업 및 주요 사양을 소개하는 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 118
      },
      {
        "id": "std-mh100-2",
        "product": "MH100",
        "no": "2",
        "category": "제품소개",
        "item": "제품 브로슈어",
        "description": "요약형 홍보물 (영업 방문·전시회용)",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 119
      },
      {
        "id": "std-mh100-3",
        "product": "MH100",
        "no": "3",
        "category": "제품소개",
        "item": "제품 소개 PPT자료",
        "description": "영업 프레젠테이션용 슬라이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 120
      },
      {
        "id": "std-mh100-4",
        "product": "MH100",
        "no": "4",
        "category": "사용/설치자료",
        "item": "사용자 매뉴얼",
        "description": "제품 사용법 안내서",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 121
      },
      {
        "id": "std-mh100-5",
        "product": "MH100",
        "no": "5",
        "category": "사용/설치자료",
        "item": "퀵 매뉴얼",
        "description": "설치 및 셋업 가이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 122
      },
      {
        "id": "std-mh100-6",
        "product": "MH100",
        "no": "6",
        "category": "사용/설치자료",
        "item": "트러블슈팅/FAQ",
        "description": "자주 묻는 질문 및 문제 해결 안내",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 123
      },
      {
        "id": "std-mh100-7",
        "product": "MH100",
        "no": "7",
        "category": "인허가/제출 자료",
        "item": "임상적 근거자료 (Clinical Evidence)",
        "description": "임상 데이터 및 관련 논문·자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 124
      },
      {
        "id": "std-mh100-9",
        "product": "MH100",
        "no": "9",
        "category": "영업지원자료",
        "item": "경쟁사 비교자료",
        "description": "경쟁 제품 대비 강점 비교 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 125
      },
      {
        "id": "std-mh100-10",
        "product": "MH100",
        "no": "10",
        "category": "영업지원자료",
        "item": "레퍼런스 병원 리스트",
        "description": "기존 설치·사용 병원 레퍼런스",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 126
      },
      {
        "id": "std-mh100-11",
        "product": "MH100",
        "no": "11",
        "category": "기타",
        "item": "사용 후기 / 케이스 스터디",
        "description": "고객 사용 사례 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 127
      },
      {
        "id": "std-mh100-12",
        "product": "MH100",
        "no": "12",
        "category": "기타",
        "item": "제품 데모 영상",
        "description": "사용 시연 영상",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 128
      },
      {
        "id": "std-mh100-13",
        "product": "MH100",
        "no": "13",
        "category": "기타",
        "item": "전시회·학회용 홍보물",
        "description": "부스 전시용 배너, 리플렛 등",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 129
      },
      {
        "id": "std-cannula-1",
        "product": "Cannula",
        "no": "1",
        "category": "제품소개",
        "item": "제품 카다로그",
        "description": "제품 라인업 및 주요 사양을 소개하는 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 130
      },
      {
        "id": "std-cannula-2",
        "product": "Cannula",
        "no": "2",
        "category": "제품소개",
        "item": "제품 브로슈어",
        "description": "요약형 홍보물 (영업 방문·전시회용)",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 131
      },
      {
        "id": "std-cannula-3",
        "product": "Cannula",
        "no": "3",
        "category": "제품소개",
        "item": "제품 소개 PPT자료",
        "description": "영업 프레젠테이션용 슬라이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 132
      },
      {
        "id": "std-cannula-4",
        "product": "Cannula",
        "no": "4",
        "category": "사용/설치자료",
        "item": "사용자 매뉴얼",
        "description": "제품 사용법 안내서",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 133
      },
      {
        "id": "std-cannula-5",
        "product": "Cannula",
        "no": "5",
        "category": "사용/설치자료",
        "item": "퀵 매뉴얼",
        "description": "설치 및 셋업 가이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 134
      },
      {
        "id": "std-cannula-6",
        "product": "Cannula",
        "no": "6",
        "category": "사용/설치자료",
        "item": "트러블슈팅/FAQ",
        "description": "자주 묻는 질문 및 문제 해결 안내",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 135
      },
      {
        "id": "std-cannula-7",
        "product": "Cannula",
        "no": "7",
        "category": "인허가/제출 자료",
        "item": "임상적 근거자료 (Clinical Evidence)",
        "description": "임상 데이터 및 관련 논문·자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 136
      },
      {
        "id": "std-cannula-9",
        "product": "Cannula",
        "no": "9",
        "category": "영업지원자료",
        "item": "경쟁사 비교자료",
        "description": "경쟁 제품 대비 강점 비교 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 137
      },
      {
        "id": "std-cannula-10",
        "product": "Cannula",
        "no": "10",
        "category": "영업지원자료",
        "item": "레퍼런스 병원 리스트",
        "description": "기존 설치·사용 병원 레퍼런스",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 138
      },
      {
        "id": "std-cannula-11",
        "product": "Cannula",
        "no": "11",
        "category": "기타",
        "item": "사용 후기 / 케이스 스터디",
        "description": "고객 사용 사례 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 139
      },
      {
        "id": "std-cannula-12",
        "product": "Cannula",
        "no": "12",
        "category": "기타",
        "item": "제품 데모 영상",
        "description": "사용 시연 영상",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 140
      },
      {
        "id": "std-cannula-13",
        "product": "Cannula",
        "no": "13",
        "category": "기타",
        "item": "전시회·학회용 홍보물",
        "description": "부스 전시용 배너, 리플렛 등",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 141
      },
      {
        "id": "std-circuit-1",
        "product": "Circuit",
        "no": "1",
        "category": "제품소개",
        "item": "제품 카다로그",
        "description": "제품 라인업 및 주요 사양을 소개하는 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 142
      },
      {
        "id": "std-circuit-2",
        "product": "Circuit",
        "no": "2",
        "category": "제품소개",
        "item": "제품 브로슈어",
        "description": "요약형 홍보물 (영업 방문·전시회용)",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 143
      },
      {
        "id": "std-circuit-3",
        "product": "Circuit",
        "no": "3",
        "category": "제품소개",
        "item": "제품 소개 PPT자료",
        "description": "영업 프레젠테이션용 슬라이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 144
      },
      {
        "id": "std-circuit-4",
        "product": "Circuit",
        "no": "4",
        "category": "사용/설치자료",
        "item": "사용자 매뉴얼",
        "description": "제품 사용법 안내서",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 145
      },
      {
        "id": "std-circuit-5",
        "product": "Circuit",
        "no": "5",
        "category": "사용/설치자료",
        "item": "퀵 매뉴얼",
        "description": "설치 및 셋업 가이드",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 146
      },
      {
        "id": "std-circuit-6",
        "product": "Circuit",
        "no": "6",
        "category": "사용/설치자료",
        "item": "트러블슈팅/FAQ",
        "description": "자주 묻는 질문 및 문제 해결 안내",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 147
      },
      {
        "id": "std-circuit-7",
        "product": "Circuit",
        "no": "7",
        "category": "인허가/제출 자료",
        "item": "임상적 근거자료 (Clinical Evidence)",
        "description": "임상 데이터 및 관련 논문·자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 148
      },
      {
        "id": "std-circuit-9",
        "product": "Circuit",
        "no": "9",
        "category": "영업지원자료",
        "item": "경쟁사 비교자료",
        "description": "경쟁 제품 대비 강점 비교 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 149
      },
      {
        "id": "std-circuit-10",
        "product": "Circuit",
        "no": "10",
        "category": "영업지원자료",
        "item": "레퍼런스 병원 리스트",
        "description": "기존 설치·사용 병원 레퍼런스",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 150
      },
      {
        "id": "std-circuit-11",
        "product": "Circuit",
        "no": "11",
        "category": "기타",
        "item": "사용 후기 / 케이스 스터디",
        "description": "고객 사용 사례 자료",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 151
      },
      {
        "id": "std-circuit-12",
        "product": "Circuit",
        "no": "12",
        "category": "기타",
        "item": "제품 데모 영상",
        "description": "사용 시연 영상",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 152
      },
      {
        "id": "std-circuit-13",
        "product": "Circuit",
        "no": "13",
        "category": "기타",
        "item": "전시회·학회용 홍보물",
        "description": "부스 전시용 배너, 리플렛 등",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 153
      },
      {
        "id": "std-omniox-hft700-2",
        "product": "OmniOx",
        "no": "2-5.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 154
      },
      {
        "id": "std-omniox-hft751-2",
        "product": "OmniOx",
        "no": "2-6.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 155
      },
      {
        "id": "std-omniox-hft700-3",
        "product": "OmniOx",
        "no": "3-2.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 156
      },
      {
        "id": "std-omniox-hft751-3",
        "product": "OmniOx",
        "no": "3-3.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 157
      },
      {
        "id": "std-omniox-hft700-6",
        "product": "OmniOx",
        "no": "6-2.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 158
      },
      {
        "id": "std-omniox-hft751-6",
        "product": "OmniOx",
        "no": "6-3.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 159
      },
      {
        "id": "std-omniox-hft700-7",
        "product": "OmniOx",
        "no": "7-2.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 160
      },
      {
        "id": "std-omniox-hft751-7",
        "product": "OmniOx",
        "no": "7-3.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 161
      },
      {
        "id": "std-omniox-hft700-8",
        "product": "OmniOx",
        "no": "8-2.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 162
      },
      {
        "id": "std-omniox-hft751-8",
        "product": "OmniOx",
        "no": "8-3.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 163
      },
      {
        "id": "std-omniox-hft700-9",
        "product": "OmniOx",
        "no": "9-2.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 164
      },
      {
        "id": "std-omniox-hft751-9",
        "product": "OmniOx",
        "no": "9-3.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 165
      },
      {
        "id": "std-omniox-hft700-10",
        "product": "OmniOx",
        "no": "10-2.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 166
      },
      {
        "id": "std-omniox-hft751-10",
        "product": "OmniOx",
        "no": "10-3.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 167
      },
      {
        "id": "std-omniox-hft700-11",
        "product": "OmniOx",
        "no": "11-2.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 168
      },
      {
        "id": "std-omniox-hft751-11",
        "product": "OmniOx",
        "no": "11-3.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 169
      },
      {
        "id": "std-omniox-hft700-12",
        "product": "OmniOx",
        "no": "12-2.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 170
      },
      {
        "id": "std-omniox-hft751-12",
        "product": "OmniOx",
        "no": "12-3.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 171
      },
      {
        "id": "std-omniox-hft700-13",
        "product": "OmniOx",
        "no": "13-2.",
        "category": "",
        "item": "HFT700",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 172
      },
      {
        "id": "std-omniox-hft751-13",
        "product": "OmniOx",
        "no": "13-3.",
        "category": "",
        "item": "HFT751",
        "description": "",
        "status": "미보유",
        "updatedAt": "",
        "note": "",
        "order": 173
      }
    ],
    "files": [],
    "navConfig": [
      {
        "id": "family-omniox",
        "type": "family",
        "parentId": "",
        "name": "OmniOx",
        "dataKey": "OmniOx",
        "mode": "child",
        "order": 1,
        "active": true
      },
      {
        "id": "product-hft700",
        "type": "product",
        "parentId": "family-omniox",
        "name": "HFT700",
        "dataKey": "HFT700",
        "mode": "",
        "order": 1,
        "active": true
      },
      {
        "id": "product-hft750",
        "type": "product",
        "parentId": "family-omniox",
        "name": "HFT750",
        "dataKey": "HFT750",
        "mode": "",
        "order": 2,
        "active": true
      },
      {
        "id": "product-hft751",
        "type": "product",
        "parentId": "family-omniox",
        "name": "HFT751",
        "dataKey": "HFT751",
        "mode": "",
        "order": 3,
        "active": true
      },
      {
        "id": "family-vent",
        "type": "family",
        "parentId": "",
        "name": "Ventilator",
        "dataKey": "Ventilator",
        "mode": "direct",
        "order": 2,
        "active": true
      },
      {
        "id": "product-mtv1000",
        "type": "product",
        "parentId": "family-vent",
        "name": "MTV1000",
        "dataKey": "MTV1000",
        "mode": "",
        "order": 1,
        "active": true
      },
      {
        "id": "product-mv2000",
        "type": "product",
        "parentId": "family-vent",
        "name": "MV2000",
        "dataKey": "MV2000",
        "mode": "",
        "order": 2,
        "active": true
      },
      {
        "id": "product-mv50",
        "type": "product",
        "parentId": "family-vent",
        "name": "MV50",
        "dataKey": "MV50",
        "mode": "",
        "order": 3,
        "active": true
      },
      {
        "id": "ed2e435f-a3db-42cc-9475-9e2de50cdd47",
        "type": "family",
        "parentId": "",
        "name": "Patient Monitor",
        "dataKey": "Patient Monitor",
        "mode": "direct",
        "order": 3,
        "active": true
      },
      {
        "id": "c24dae67-38a0-446c-b52e-80ccd2df6d77",
        "type": "product",
        "parentId": "ed2e435f-a3db-42cc-9475-9e2de50cdd47",
        "name": "MP10/12",
        "dataKey": "MP10/12",
        "mode": "",
        "order": 1,
        "active": true
      },
      {
        "id": "family-pulse-oximeter",
        "type": "family",
        "parentId": "",
        "name": "Pulse Oximeter",
        "dataKey": "",
        "mode": "direct",
        "order": 4,
        "active": true
      },
      {
        "id": "product-mp800",
        "type": "product",
        "parentId": "family-pulse-oximeter",
        "name": "MP800",
        "dataKey": "MP800",
        "mode": "",
        "order": 1,
        "active": true
      },
      {
        "id": "family-airway-management",
        "type": "family",
        "parentId": "",
        "name": "Airway Management",
        "dataKey": "",
        "mode": "direct",
        "order": 5,
        "active": true
      },
      {
        "id": "product-mnc100",
        "type": "product",
        "parentId": "family-airway-management",
        "name": "MNC100",
        "dataKey": "MNC100",
        "mode": "",
        "order": 1,
        "active": true
      },
      {
        "id": "product-mh100",
        "type": "product",
        "parentId": "family-airway-management",
        "name": "MH100",
        "dataKey": "MH100",
        "mode": "",
        "order": 2,
        "active": true
      },
      {
        "id": "family-acc",
        "type": "family",
        "parentId": "",
        "name": "Accessories",
        "dataKey": "",
        "mode": "direct",
        "order": 6,
        "active": true
      },
      {
        "id": "product-cannula",
        "type": "product",
        "parentId": "family-acc",
        "name": "Cannula",
        "dataKey": "Cannula",
        "mode": "",
        "order": 1,
        "active": true
      },
      {
        "id": "product-circuit",
        "type": "product",
        "parentId": "family-acc",
        "name": "Breathing Circuit",
        "dataKey": "Circuit",
        "mode": "",
        "order": 2,
        "active": true
      }
    ]
  }
};
